/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xyz_fanqi_androidclog_JNIBridge */

#ifndef _Included_xyz_fanqi_androidclog_JNIBridge
#define _Included_xyz_fanqi_androidclog_JNIBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xyz_fanqi_androidclog_JNIBridge
 * Method:    logI
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_xyz_fanqi_androidclog_JNIBridge_logI
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
