/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xyz_fanqi_hellojni_JNIBridge */

#ifndef _Included_xyz_fanqi_hellojni_JNIBridge
#define _Included_xyz_fanqi_hellojni_JNIBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xyz_fanqi_hellojni_JNIBridge
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_xyz_fanqi_hellojni_JNIBridge_getString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
